#include <iostream>
#include <string>

using namespace std;

int main(){
	string a;
	cout << "Type any word you want (e.g. Computer): ";
	cin >> a;
	
	if (a == "Computer"){
		cout << "It is an electronic device that can process, store, receive, and output data. It is a device that can transform data into meaningful information";
	}else if(a == "Abacus"){
		cout << "The first computer and is basically made of a wooden rack that has metal rods with beads mounted on it.";
	}else if(a == "Napier's Bones"){
		cout << "It was a manually operated calculating device and was invented by John Napier.";
	}else if(a == "Pascaline"){
		cout << "It is also called an Arithmetic Machine or Adding Machine.";
	}else if(a == "Stepped Reckoner"){
		cout << "It was made of flute drums.";
	}else if(a == "Analytical Engine"){
		cout << "Invented by Charles Babbage and was a mechanical computer that used punch cards as input.";
	}else if(a == "Tabulating Machine"){
		cout << "A mechanical tabulator that was based on punch cards.";
	}else if(a == "Mark I"){
		cout << "A machine that could perform large calculations.";
	}else if(a == "Vacuum Tubes"){
		cout << "It was used as the basic components of CPU and memory.";
	}else if(a == "Transistor"){
		cout << "These are compact and consume less power, faster than first generation computer.";
	}else if(a == "First Generation Computers"){
		cout << "Period of the year 1940-1956, computers are slow, huge, and expensive.";
	}else if(a == "Second Generation Computers"){
		cout << "Period of the year 1957-1963, it was the creation of transistors.";
	}else if(a == "Third Generation Computers"){
		cout << "Period of the year 1964-1971, integrated circuits were used instead of transistor.";
	}else if(a == "Digital Computer"){
		cout << "It is capable of processing information in discrete form.";
	}else if(a == "Analog Computer"){
		cout << "It is used to process data generated by ongoing physical processing.";
	}else if(a == "Hybrid Computer"){
		cout << "It is used as a cost effective means for complex simulations.";
	}else if(a == "Supercomputer"){
		cout << "";
	}else if(a == "Mainfraim Computer"){
		cout << "The most expensive and powerful computer used in fields such as weather forecasting, cryptography, and nuclear research.";
	}else if(a == "Minicomputer"){
		cout << "Large and powerul computer that can be used by large organizations such as banks, airlines, and government agencies.";
	}else if(a == "Personal Computer"){
		cout << "This are small and affordable computer designed for individual users and commonly used for personal productivity, entertainment, and communication.";
	}else if(a == "Workstation"){
		cout << "This are high performance computers that are used by professionals such as engineering, architecture, and designer.";
	}else if(a == "Embedded System"){
		cout << "A specialized computers that are built in devices such as cars, appliances, and medical equipment.";
	}else if(a == "Mobile Devices"){
		cout << "A small and portable computers designed for on-the-go use such as smartphones, laptops, and tablets.";
	}else if(a == "Peripheral Devices"){
		cout << "It is used for performing the specific functions and are connected to the computer externally.";
	}else if(a == "RAM"){
		cout << "Random Access Memory, an electronic device that is volatile, much more faster in speed, and allows fast data processing and multitasking.";
	}else if(a == "Hard Disk Drive"){
		cout << "An electromechanical device that is non-volatile, its speed is slower than electronic device, has no connection with CPU, and used for long-term storage of data.";
	}else if(a == "System Software"){
		cout << "A software, which our PC, it won't run - a must for a device to be operated. For example: Linux, Unix, Windows.";
	}else if(a == "Application Software"){
		cout << "A software, which our PC, it can run. It is not necessary for device to be operated. For example: Facebook, Instagram, and Games.";
	}else if(a == "Hacker"){
		cout << "A type of malicious person who will just warn you something about malicious activity going around in your computer. It will not steal your information.";
	}else if(a == "Cracker"){
		cout << "They will try to steal your information without informing you.";
	}else{
		cout << "No word found. Please try again.";
	}
	return 0;
}